import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/toaster";
import { Users2 } from 'lucide-react';

import "./globals.css";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <SessionProvider>
          <header className={"fixed h-20 flex flex-row justify-between items-center px-12 w-full bg-indigo-300"}>
            <h1>
              We Need a Brand Name
            </h1>
            <Button variant="outline" className="rounded-full w-12 h-12 p-0 border-4">
              <Users2 size={20} strokeWidth={2}></Users2>
            </Button>
          </header>
          <main className="fixed top-20 w-full">
          {children}
          </main>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
